services:
  web:
    build:
      context: ./fastapi_app
      dockerfile: Dockerfile
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; uvicorn fastapi_app.main:app --host 0.0.0.0 --reload'
    environment:
      - CRYPTID_UNIT_TEST=0
      - DATABASE_URL=postgresql://fastapi_traefik:fastapi_traefik@db:5432/fastapi_traefik
    volumes:
      - ./fastapi_app:/fastapi_app
    ports:
      - 8008:8000
    depends_on:
      - db  
  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5435:5432
    environment:
      - POSTGRES_USER=fastapi_traefik
      - POSTGRES_PASSWORD=fastapi_traefik
      - POSTGRES_DB=fastapi_traefik
volumes:
  postgres_data:  