

services:
  web:
    build:
      context: ./fastapi_app
      dockerfile: Dockerfile
    command: uvicorn fastapi_app.auth:app --host 0.0.0.0 --reload
    volumes:
      - ./fastapi_app:/fastapi_app
    ports:
      - 8008:8000