"""empty message

Revision ID: 55b98fdf736c
Revises: 8c14a626c21e
Create Date: 2024-12-20 15:03:00.553661

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '55b98fdf736c'
down_revision: Union[str, None] = '8c14a626c21e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('query', sa.Column('query', sa.String(), nullable=False))
    op.drop_constraint('query_phrase_key', 'query', type_='unique')
    op.create_unique_constraint(None, 'query', ['query'])
    op.drop_column('query', 'phrase')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('query', sa.Column('phrase', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'query', type_='unique')
    op.create_unique_constraint('query_phrase_key', 'query', ['phrase'])
    op.drop_column('query', 'query')
    # ### end Alembic commands ###
