"""empty message

Revision ID: 8c14a626c21e
Revises: eda9fad806fe
Create Date: 2024-12-17 14:48:10.162996

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8c14a626c21e'
down_revision: Union[str, None] = 'eda9fad806fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('position',
                    sa.Column('position_id', sa.Integer(), nullable=False),
                    sa.Column('vkgroup_id', sa.Integer(), nullable=True),
                    sa.Column('query_id', sa.Integer(), nullable=True),
                    sa.Column('position', sa.Integer(), nullable=False),
                    sa.Column('created_at', sa.DateTime(timezone=True),
                              server_default=sa.text('now()'), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['query_id'], ['query.query_id'], ),
                    sa.ForeignKeyConstraint(
                        ['vkgroup_id'], ['vkgroup.vkgroup_id'], ),
                    sa.PrimaryKeyConstraint('position_id')
                    )
    op.drop_table('parse_ivent')
    op.create_unique_constraint(None, 'query', ['phrase'])
    op.create_unique_constraint(None, 'vkgroup', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'vkgroup', type_='unique')
    op.drop_constraint(None, 'query', type_='unique')
    op.create_table('parse_ivent',
                    sa.Column('parse_ivent_id', sa.INTEGER(),
                              autoincrement=True, nullable=False),
                    sa.Column('vkgroup_id', sa.INTEGER(),
                              autoincrement=False, nullable=True),
                    sa.Column('query_id', sa.INTEGER(),
                              autoincrement=False, nullable=True),
                    sa.Column('position', sa.INTEGER(),
                              autoincrement=False, nullable=False),
                    sa.Column('at_time', postgresql.TIMESTAMP(timezone=True),
                              server_default=sa.text('now()'),
                              autoincrement=False, nullable=False),
                    sa.ForeignKeyConstraint(
                        ['query_id'], ['query.query_id'],
                        name='parse_ivent_query_id_fkey'),
                    sa.ForeignKeyConstraint(
                        ['vkgroup_id'], ['vkgroup.vkgroup_id'],
                        name='parse_ivent_vkgroup_id_fkey'),
                    sa.PrimaryKeyConstraint(
                        'parse_ivent_id', name='parse_ivent_pkey')
                    )
    op.drop_table('position')
    # ### end Alembic commands ###
