"""Init

Revision ID: eda9fad806fe
Revises: 
Create Date: 2024-12-12 11:09:41.510963

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eda9fad806fe'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('query',
    sa.Column('query_id', sa.Integer(), nullable=False),
    sa.Column('phrase', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('query_id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('hash', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vkgroup',
    sa.Column('vkgroup_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('vkgroup_id')
    )
    op.create_table('parse_ivent',
    sa.Column('parse_ivent_id', sa.Integer(), nullable=False),
    sa.Column('vkgroup_id', sa.Integer(), nullable=True),
    sa.Column('query_id', sa.Integer(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('at_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['query_id'], ['query.query_id'], ),
    sa.ForeignKeyConstraint(['vkgroup_id'], ['vkgroup.vkgroup_id'], ),
    sa.PrimaryKeyConstraint('parse_ivent_id')
    )
    op.create_table('vkgroup_query',
    sa.Column('vkgroup_id', sa.Integer(), nullable=False),
    sa.Column('query_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['query_id'], ['query.query_id'], ),
    sa.ForeignKeyConstraint(['vkgroup_id'], ['vkgroup.vkgroup_id'], ),
    sa.PrimaryKeyConstraint('vkgroup_id', 'query_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vkgroup_query')
    op.drop_table('parse_ivent')
    op.drop_table('vkgroup')
    op.drop_table('user')
    op.drop_table('query')
    # ### end Alembic commands ###
