"""empty message

Revision ID: a0fac7276948
Revises: 
Create Date: 2024-12-25 14:44:28.943343

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a0fac7276948'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('hash', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vkgroup',
    sa.Column('vkgroup_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('vkgroup_id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('query',
    sa.Column('query_id', sa.Integer(), nullable=False),
    sa.Column('query', sa.String(), nullable=False),
    sa.Column('vkgroup_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['vkgroup_id'], ['vkgroup.vkgroup_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('query_id'),
    sa.UniqueConstraint('query')
    )
    op.create_table('position',
    sa.Column('position_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('query_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['query_id'], ['query.query_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('position_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('position')
    op.drop_table('query')
    op.drop_table('vkgroup')
    op.drop_table('user')
    # ### end Alembic commands ###
