"""empty message

Revision ID: 916f68fa65fd
Revises: a0fac7276948
Create Date: 2024-12-26 11:41:40.396120

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '916f68fa65fd'
down_revision: Union[str, None] = 'a0fac7276948'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vkgroup', sa.Column('members', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vkgroup', 'members')
    # ### end Alembic commands ###
